### PR TITLE
Add Solano County Scraper, README

### PR DESCRIPTION
**Pull request by miloconway**

### CODE REVIEW

**Comment by typpo** [comment]
This is really awesome!  Solano and Napa are our only remaining Bay Area counties.  A couple comments:

- Looks like you may have gotten the 2018 parcels data.  2020 is in the same format so shouldn't be a big deal to use instead (I'd guess the differences are minor): [link](https://geohub-doitgis.opendata.arcgis.com/datasets/parcels2020?geometry=-124.169%2C37.911%2C-119.829%2C38.666)
- In order to get latlng, you'll have to download it in shapefile format, then either read in the shapefiles directly or convert it to a different readable format such as geojson (I do this with a program called `ogr2ogr` with this command: `ogr2ogr -f GeoJSON solano.geojson solano.shp`)
- These records from shapefile will have latlngs associated with them that you can use to compute the centroid.  Here's an example record:
```
{ "type": "Feature", "properties": { "OBJECTID": 46, "APN": "0080370290", "created_us": null, "created_da": null, "last_edite": null, "Shape_Leng": 120.116047431, "Shape__Are": 113.625, "Shape__Len": 46.529728260132302 }, "geometry": { "type": "Polygon", "coordinates": [ [ [ -122.151833739051, 38.044821181391697 ], [ -122.151829397114, 38.044826250827299 ], [ -122.151821539978997, 38.044822238895598 ], [ -122.151860462795, 38.044768683059999 ], [ -122.151850972199995, 38.044764159802298 ], [ -122.151868974192993, 38.044736766274703 ], [ -122.151924535608998, 38.044754025261803 ], [ -122.151922190795005, 38.044760269476498 ], [ -122.151945979160999, 38.044770936565499 ], [ -122.151890214025997, 38.044847023424303 ], [ -122.151833739051, 38.044821181391697 ] ] ] } },
```

I've converted the parcels datafile to geojson with latlngs.  Here it is if you would like to use it:
[solano.geojson.gz](https://github.com/typpo/ca-property-tax/files/5396852/solano.geojson.gz)

**Comment by miloconway** [comment]
Thank you for the feedback, I've updated and ran the scraper and parser through.

Outstanding issues:
- How to share / upload scraped data?
- ~~Need to generate the "tax lookup" URL in the lookup view~~
- ~~Need to find some way to derive the city from the APN. The address but not the city is located in the scraped data, and there are no address in the Shapefile that I saw~~

EDIT: guess don't need the city

**Comment by typpo** [comment]
This looks really great.  To share the data, most people have just been uploading it to Google Drive and sharing the link.  If you gzip the parsed output it may even be small enough that you can attach it to this github issue.

Once I have the parsed output, I can add it to the public site in a matter of minutes!  Also let me know how you'd like to be credited on the map (name? link to website or twitter?)

**Comment by miloconway** [comment]
[Here](https://drive.google.com/drive/folders/1-ycrybqmfPCwTz9fwMIN4QXb84hnpVxe?usp=sharing) you go!

Just by name is enough: Andy Lin

**Comment by typpo** [comment]
This is available on the live site now.  Thank you Andy :100:

**Pull request merged**
